### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by smira2000** [deniaz/wp-dms#6]
Hi Deniaz, thanks for the amazing module.
It works very well and is well coded/commented.

I am trying to understand how the actual domain rewriting is actually working here. I've read through all the code and comments in dms.class.php but i can't fint any clues as tho how this is actually happening.

My goal is to add a field to a cpt that creates the domain map instead of having to do it from the dms settings page.

This might also be interesting to you to add as a feature?
ie. add custom mapping field option to all pages/posts/_my custom post type_

Thanks again,
-miro

**Comment by deniaz** [comment]
Hi Miro,

I'll need to update the WP plugin directory ;) have a look at this site: http://deniaz.github.com/wp-dms/

It says:

> DMS will analyse HTTP requests and check if the domain is mapped to WordPress content. If so, DMS will load the corresponding content. Otherwise, it will not do anything and let WordPress do its magic

which in code means:

`add_action('init', array('DMS', 'run'), 1, 1); // dms.php`

This means `DMS::run()` is hooked to WordPress init. `DMS::run()` generates the domain <-> page map (associative array). If the current domain (`$_SERVER["HTTP_HOST"]`) matches a post, it will run `DMS::map()` ([line 215](https://github.com/deniaz/wp-dms/blob/master/dms/dms.class.php#L215)). `DMS::map()` checks the mapped value, and decides what to load (by using `query_posts()` if it's a page, post or cpt) or does some more logic for categories and archives. 

After `query_posts()` is called, DMS is done. WordPress will then load the desired content, continue to load templates, yadda yadda.

Unfortunately the code is not very well written (it was my first wp plugin) and I really want to rewrite the code. I've thought of the feature you're describing before but I was - and I'm being really honest with you know - just too lazy to implement it ;) 

It shouldn't be too much of a problem. Instead of creating the form in a options-page, you'd just add a field to the cpt.

If you're implementing this feature, don't hesitate to send me a pull request. If you have any further questions, don't hesitate to ask!

**Comment by smira2000** [comment]
Ahh... ofcourse....
For some reason I had it in my mind that you where rewriting the domain with some invisible wizardry!
This makes a lot more sense now so i'll go ahead and take a stab at it.
Thanks for the super fast reply and helpfulness, i'll let you know how it goes!
